# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10


[[main]]
  name = "Research topics"
  url = "#research_topics"
  weight = 30

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

[[main]]
  name = "CV"
  url = "/cv"
  weight = 45

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

#[[main]]
#  name = "Projects"  # Title of the link.
#  url = "research_projects/"  # Widget Page folder name.
#  weight = 80  # Position of the link in the navigation bar.
